- id: doi:10.3835/plantgenome2012.05.0005
  image: https://acsess.onlinelibrary.wiley.com/cms/asset/1b72a9c4-f075-4290-a68c-cf4d7aa187d6/tpg2plantgenome2012050005-fig-0003-m.jpg
  tags:
    - genotyping
    - review
    - gbs

- id: doi:10.2135/cropsci2013.08.0579
  image: https://raw.githubusercontent.com/PhenoApps/Field-Book/master/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  repo: PhenoApps/Field-Book
  extra-links:
    - type: source
      link: https://github.com/PhenoApps/Field-Book
      text: Source
  tags:
    - phenoapps
    - plant breeding

- id: doi:10.1186/s12864-015-1404-9
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12864-015-1404-9/MediaObjects/12864_2015_1404_Fig3_HTML.gif?as=webp
  tags:
    - genotyping
    - gbs

- id: doi:10.1111/gcb.13163
  image: images/publications/tack2015.jpg
  tags:
    - climate change
    - wheat

- id: doi:10.3835/plantgenome2018.01.0004
  image: https://acsess.onlinelibrary.wiley.com/cms/asset/f26a7604-f2ef-4266-abc1-bc16a5705af3/tpg2plantgenome2018010004-fig-0001-m.jpg
  tags:
    - wheat
    - plant breeding

- id: doi:10.2135/cropsci2018.01.0073
  image: images/publications/rife2019.png
  tags:
    - wheat
    - plant breeding

- id: doi:10.1007/s00122-018-3107-5
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00122-018-3107-5/MediaObjects/122_2018_3107_Fig1_HTML.png?as=webp
  tags:
    - wheat
    - pre-harvest sprouting

- id: doi:10.1093/bioinformatics/btz190
  image: images/publications/selby2019.png
  repo: plantbreeding/BrAPI
  extra-links:
    - type: source
      link: https://github.com/plantbreeding/BrAPI
      text: Source
  tags:
    - api

- id: doi:10.1007/s00122-020-03712-y
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1007%2Fs00122-020-03712-y/MediaObjects/122_2020_3712_Fig4_HTML.png?as=webp
  tags:
    - wheat

- id: doi:10.1002/ppj2.20024
  image: https://raw.githubusercontent.com/PhenoApps/Prospector/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  repo: PhenoApps/Prospector
  extra-links:
    - type: source
      link: https://github.com/PhenoApps/Prospector
      text: Source
  tags:
    - phenoapps
    - NIR

- id: doi:10.1002/csc2.20702
  image: https://raw.githubusercontent.com/PhenoApps/Intercross/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  repo: PhenoApps/Intercross
  extra-links:
    - type: source
      link: https://github.com/PhenoApps/Intercross
      text: Source
  tags:
    - phenoapps
    - plant breeding

- id: doi:10.1093/g3journal/jkac078
  image: images/publications/morales2022.png
  extra-links:
    - type: source
      link: https://github.com/solgenomics/sgn/
      text: Source
  tags:
    - database
